#!/bin/sh

#
# git keep - Add a directory to git
#

set -e

SELF="keep"
KEEP=".gitkeep"
TEXT="# Tracked on $(date +%Y-%m-%d)"

err() {
	echo "ERROR: $*" 1>&2
}

die() {
	err "$*"
	exit 1
}

if [ ! "$#" -eq "1" ]
then
	die "'${SELF}' expects exactly ONE argument: <directory>"
fi

if [ ! -d "$1" ]
then
	die "'$1' is not a valid directory"
fi

echo "${TEXT}" > "${1}/${KEEP}"
git add "${1}/${KEEP}"
git commit -m "Added ${1}" "${1}/${KEEP}"

