#!/bin/sh

#
# git ignore - Generate a .gitignore file in the current directory
#

set -e

IGNORE=".gitignore"
API="https://www.gitignore.io/api/<type>"

err() {
	echo "ERROR: $*" 1>&2
}

die() {
	err "$*"
	exit 1
}

has() {
	if [ -x "$(command -v "$1")" ]
	then
		return 0
	fi

	return 1
}

ignore() {
	if has wget
	then
		wget -O "${IGNORE}" "$(echo "${API}" | sed "s/<type>/$1/g")"
	elif has curl
	then
		curl
	fi
}

while [ "$#" -gt 0 ]
do
	case "$1" in
		*) ignore "$1" ;;
	esac

	shift
done
