#!/bin/sh

#
# git ignore - Generate a .gitignore file in the current directory
#

set -e

SELF="ignore"
IGNORE=".gitignore"
API="https://www.gitignore.io/api/<type>"

err() {
	echo "ERROR: $*" 1>&2
}

die() {
	err "$*"
	exit 1
}

ignore() {
	echo "${API}" | sed "s/<type>/$1/g"
}

while [ "$#" -gt 0 ]
do
	case "$1" in
		*) ignore "$1" ;;
	esac

	shift
done
