#!/bin/sh

#
# git keep - Add a directory to git
#
# usage:
# 	git keep [OPTIONS] DIR1 [DIR2 DIR3 ...]
#
# options:
# 	-m
# 		Call `mkdir -p` on every DIR to ensure it exists before
# 		attempting to keep them.
#
# DIRS:
# 	The directory or directories to keep, at least one must be
# 	provided, and duplicates are ignored, the last instance of each
# 	DIR found is used. This may affect the timestamp if run at exactly
# 	midnight, but should otherwise be of no consequence.
#

set -e

KEEP=".gitkeep"
TEXT="# Tracked on $(date +%Y-%m-%d)"

err() {
	echo "ERROR: $*" 1>&2
}

die() {
	err "$*"
	exit 1
}

keep() {
	if [ ! -d "$1" ]
	then
		if [ "$MKDIR" = "TRUE" ]
		then
			mkdir -p "$1"
		else
			die "'$1' is not a valid directory"
		fi
	fi

	echo "${TEXT}" > "${1}/${KEEP}"
	git add "${1}/${KEEP}"
	git commit -m "Added ${1}" "${1}/${KEEP}"
}

while [ "$#" -gt 0 ]
do
	case "$1" in
		"-m") MKDIR="TRUE" ;;
		*)    keep "$1"    ;;
	esac

	shift
done
