---

name: shellcheck

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
