---

name: shellcheck

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck git-keep
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          additional_files: git-keep
